const Data = {
    status: "success",
    items: [
        {
            id: 1,
            title: "Agility Gold - Grandes Adultos",
            price: 59.607,
            image: require('../Imagenes/Agility Gold - Grandes Adultos.jpg'),
            category: "alimento",
            mascota: "perro",
            caracteristicas: "Agility Gold - Grandes Adultos, esta compuesta por cordero, arroz cristal, Harina de pollo, almidón de papa, Salmón, Aceite de Pollo, celulosa, Mogolla de trigo, Digerido enzimático, Cloruro de Potasio, Cloruro de sodio (sal), Fosfato dicálcico, mezcla de silicatos, Manano-oligosacáridos de la ((no-GM) Saccharomyces cerevisiae, carbonato de calcio, vitamina E tocoferol acetato, vitamina B3 niacinamida, vitamina B5 calpan, vitamina AD3, vitamina H biotina, vitamina B2 riboflavina, vitamina K3 ,menadiona, vitamina B12 cianocobalamina hplc, vitamina B6 piridoxina hcl, vitamina B1 tiamina mononitrato, vitamina B9 ácido fólico, proteinato de zinc; Mananoproteina, extracto de yuca shidiguera, Selenio levadura, Harina de alga achizochytrium sp., Oxido de Manganeso; Sulfato Ferroso; Sulfato de cobre; Yodato de Calcio; Selenio Quelado; Sales de Ácido Propiónico; sulfato de zinc, sulfato ferroso, carbonato de calcio, caolin, sulfato de cobre, px eddi, sulfato de manganeso, selenito de sodio ,Vitamina A; Vitamina D3; Vitamina E; Vitamina B12; Tiamina, Riboflavina, Niacina, Pantotenato de Calcio, Piridoxina, Ácido Fólico, Taurina, aceite esencial de romero (Rosmarinus officinalis Proteína mínimo 24.0% Grasa mínimo 15.0% Fibra máximo 4.0% Ceniza máximo 8.0% Humedad máximo 11.0%",
            descripcion: "Agility Gold - Grandes Adultos, es una fórmula especialmente creada para la nutrición de la piel y pelaje de perros adultos, utilización de macro nutrientes naturales como carne de verdad (salmón y cordero), que proporcionan una mayor palatabilidad, mayor digestibilidad apoyando el desarrollo óptimo de las mascotas. es una alimento de alta calidad con utilización de algas marinas para potencializar acciones en la hidratación de la piel y aceites botánicos de romero que evitan el envejecimiento celular dando fuerza y brillo al pelaje.",
            img1: "https://d23qt3x1ychzdy.cloudfront.net/images_products/20d69e274934e018d115ae06066611ad.jpg",
            img2: ".jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
            cantidad: 1,
        },
        {
            id: 2,
            title: "Royal Canin - Fbn Persian Adult",
            price: 150.544,
            image: require('../Imagenes/Royal Canin - Fbn Persian Adult.jpg'),
            category: "alimento",
            mascota: "gato",
            caracteristicas: "Proteínas de ave deshidratadas, grasas animales, arroz, aislado de proteínas vegetales*, harina de maíz, fibras vegetales, hidrolizado de proteínas animales, gluten de maíz, harina de trigo, maíz, levaduras completas y partes de las mismas, minerales, pulpa de achicoria, aceite de pescado, semillas e integumentos de psyllium (1%), aceite de soja, fructo-oligosacáridos, hidrolizado de levaduras (fuente de manano-oligosacáridos), aceite de borraja, extracto de rosa de la India (fuente de luteína). Aditivos (por kg): Aditivos nutricionales: Vitamina A: 31000 UI, Vitamina D3: 800 UI, E1 (Hierro): 36 mg, E2 (Yodo): 3,6 mg, E4 (Cobre): 11 mg, E5 (Manganeso): 47 mg, E6 (Zinc): 140 mg, E8 (Selenio): 0,08 mg - Aditivos tecnológicos: Clinoptilolita de origen sedimentario: 10 g - Conservantes - Antioxidantes.Componentes analíticos: Proteína bruta: 30% - Grasa bruta: 22% - Ceniza bruta: 7,4% - Fibra bruta: 4,7% - Por kg: Ácidos grasos omega 6: 48,4 g - Ácidos grasos omega 3: 11 g.",
            descripcion: "Royal Canin Fbn Persian Adult es una nutrición hecha a medida creada solo para la raza persa. La croqueta especializada en forma de almendra está diseñada para la forma única en que un gato persa usa la parte inferior de la lengua para comer, lo que permite que los gatos recojan, mastiquen y eliminen fácilmente la acumulación de sarro. Una combinación exclusiva de nutrientes esenciales como aminoácidos, vitaminas y ácidos grasos omega-6 y omega-3 promueve una piel saludable y un pelaje saludable, manteniendo el largo y lujoso pelaje de tu persa brillante y suave. Una mezcla compleja de fibras ayuda a eliminar el cabello ingerido y controlar las bolas de pelo.\n",
            img1: "https://d23qt3x1ychzdy.cloudfront.net/dev_images_products/3607_61905_Royal_Canin_Fbn_Persian_Adult_1616613293_2176x2168.jpg",
            img2: ".jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
            cantidad: 1,
        },
        {
            id: 3,
            title: "Let´s Play - Pelota",
            price: 15.255,
            image: require('../Imagenes/Let´s Play - Pelota.jpg'),
            category: "juguetes",
            mascota: "perro",
            caracteristicas: "Pelota maciza de 6,5 cm de diametro, ideal para razas pequeñas y destructivas.",
            descripcion: "Pelota en goma grado alimentos, completamente maciza con textura en forma de huella",
            img1: "https://d23qt3x1ychzdy.cloudfront.net/dev_images_products/de1d295d34182828d3745be12422f98e_1702922110.jpg",
            img2: ".jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
            cantidad: 1,
        },
        {
            id: 4,
            title: "Marca Gato - Rascador Wafle",
            price: 224.818,
            image: require('../Imagenes/Marca Gato - Rascador Wafle_1.jpg'),
            category: "juguetes",
            mascota: "gato",
            caracteristicas: "Rascador para gatos en cartón corrugado doble pared. Todo su exterior e interior son áreas de rascado. Su altura permite el rascado vertical. Tiene dos niveles de rascado y descanso. Es un rascador estable y robusto con un diseño que armoniza con tu hogar. Se usa por ambos lados. Medidas: Largo 73 cm x ancho 35 cm x alto 27 cm Basamos los diseños de nuestros rascadores en nuestra formación y experiencia en etología en donde estudiamos y observamos la conducta de rascado de los gatos para crear elementos que realmente funcionen como rascadores y zonas de descanso. Además buscamos diseños que armonicen con tu hogar y se integren a tu decoración. Los frontales son tapizados de alta calidad que aseguran que tu gato no las dañe ni con las uñas ni con sus muelitas. Utilizamos textiles antirasguños. Todo el exterior e interior del rascador son zonas de rascado lo que hace que sea un rascador para gatos con 4 áreas aprovechables para rascar rascar. La altura de la rasca cueva permite el rascado vertical. Nuestro producto es 100% colombiano. Apoya lo nuestro.",
            descripcion: "Un rascador para gatos potente, con áreas de rascado amplias y realmente aprovechables. Diseño estético, minimalista y compacto. Tu gato amará este rascador por su comodidad para rasguñar y descansar.",
            img1: "https://d23qt3x1ychzdy.cloudfront.net/dev_images_products/82727_Marca_Gato_____Rascador_Wafle____Entrega_en_4_d__as_h__biles____1665605222_0_800x800.jpg",
            img2: ".jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
            cantidad: 1,
        },
        {
            id: 5,
            title: "Simparica - Perros De 10 Hasta 20 Kg.",
            price: 43.500,
            image: require('../Imagenes/Simparica - Perros De 10 Hasta 20 Kg..jpg'),
            category: "farmacia",
            mascota: "perro",
            caracteristicas: "Sustancia activa: Sarolaner 40 mg. Excipientes: Succinato de acetato de hipromelosa, de grado medio. Lactosa monohidrato. Glicolato de sodio de almidón. Sílice coloidal anhidra. Estearato de magnesio. Almidón de maíz. Azúcar. Glucosa líquida (81,5% sólidos). Polvo seco de hígado porcino. Hidrolizado de proteína vegetal. Gelatina tipo A. Germen de trigo. Hidrogenofosfato de calcio anhidro.",
            descripcion: "Simparica Antipulgas y Garrapatas para perros se administra por via oral una vez al mes y está formulado para el tratamiento y control de infestaciones de pulgas y garrapatas. Es una tableta masticable con sabor palatable cuyo efecto empezará 3 horas después de que se haya consumido la tableta y se extenderá hasta el día 35, protegiendo de forma segura a tu perro por más tiempo.",
            img1: "https://d23qt3x1ychzdy.cloudfront.net/dev_images_products/69146_Simparica_40_Mg_1627583703_0_500x500.jpg",
            img2: ".jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
            cantidad: 1,
        },
        {
            id: 6,
            title: "Total Full LC - Gatos.",
            price: 26.100,
            image: require('../Imagenes/Total Full LC - Gatos.jpg'),
            category: "farmacia",
            mascota: "gato",
            caracteristicas: "Está elaborado a partir de Fenbendazol, Pirantel y Prazicuantel, Fuertes compuestos que trabajarán en conjunto para generar disminución de energía y muerte al parásito, generar bloqueo neuromuscular produciendo parálisis y parálisis espástica con daño tegumental a parásitos internos como los helmintos.",
            descripcion: "Total Full LC es un antiparasitario para gatos interno de amplio espectro que está formulado para el control y tratamiento de cestodes y nematodes que pueden afectar el organismo de los gatos. Es un antiparasitario de liberación controlada y suministro oral que actuará eficazmente protegiendo la salud de tu gato. Además, será muy fácil suministrarlo gracias a su palatable sabor.",
            img1: "https://d23qt3x1ychzdy.cloudfront.net/dev_images_products/2969_139001_Total_Full_LC___Gatos__1645652954_500x500.jpg",
            img2: ".jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
            cantidad: 1,
        },
        {
            id: 7,
            title: "Furminator - Deslanador Perro Grande Pelo Largo",
            price: 137.050,
            image: require('../Imagenes/Furminator - Deslanador Perro Grande Pelo Largo.jpg'),
            category: "cuidado e higiene",
            mascota: "perro",
            caracteristicas: "Cepillo para deslanado semanal. Mango ergonómico: para un manejo cómodo y sencillo. Botón FURejector: limpia y retira el pelo suelto de la herramienta con facilidad. Borde de acero inoxidable.",
            descripcion: "Cepillo Furminator Deslanador Perro pequeño, es esencial para razas pequeñas, viene para pelo largo, elimina hasta el 99 % del pelo suelto procedente de la muda. Úselo 1 o 2 veces a la semana en sesiones de 10 a 20 minutos sobre el pelo seco. Tu conoces a tu peludo y sabes cuando asearlo, pero es difícil saber la frecuencia, y si lo estás haciendo bien. Furminator está aquí para ayudarle. El Furminator Ultimate Hair Reduction System ha sido diseñado para ayudar a reducir el pelo de los peludos en tu hogar de la forma más fácil.",
            img1: "https://d23qt3x1ychzdy.cloudfront.net/dev_images_products/ccb6db55e1dd603a159a3dfd120fb886_1675192391.jpg",
            img2: ".jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
            cantidad: 1,
        },
        {
            id: 8,
            title: "Furry - Arena Super Premium para Gato Carbón Activado",
            price: 59.073,
            image: require('../Imagenes/Furry - Arena Super Premium para Gato Carbón Activado.jpg'),
            category: "cuidado e higiene",
            mascota: "gato",
            caracteristicas: "Arena sanitaria para gato, compuesta de Bentonita de calcio 100% natural. No contiene aditivos, químicos o minerales metálicos. Con carbón activado antibacterial para mayor efecto en control de olores y mayor duración. Excelentes propiedades de aglomeración absorción. Arena paletizada.",
            descripcion: "Furry super premium con carbón activado, es una arena para gatos 100% natural, hecho a base de bentonita de calcio y carbón activado de máxima calidad. Tamaño de la mascota: Todos los Tamaños. Etapa de la vida: Todas las Edades.",
            img1: "https://laikapp.s3.amazonaws.com/dev_images_products/1db364de8dba10f8455c4071522b4cf6_1713296229.jpg",
            img2: ".jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
            cantidad: 1,
        },
        {
            id: 9,
            title: "Dog Yurt - Chunky Nutribar Snack para Perros",
            price: 59.607,
            image: require('../Imagenes/Dog Yurt - Chunky Nutribar Snack para Perros.jpg'),
            category: "snacks",
            mascota: "perro",
            caracteristicas: "Snack para perros de todas las razas. Topping hecho con salmón, arándanos y alimentos líquido no lácteo con probióticos, hecho a base de agua. Exclusivo para perros. No es apto para consumo humano.",
            descripcion: "Dogyurt: un snack equilibrado y delicioso para perros adultos de todas las razas. Irresistible en sabor y nutritivo, promueve el bienestar general de tu mascota. Es más que un premio; es un regalo para consentir a tu perro con un momento sabroso y saludable. Para perros de todas las razas y tamaños a partir de los 6 meses de edad. Snack para perros de todas las razas. Topping hecho con salmón, arándanos y alimentos líquido no lácteo con probióticos, hecho a base de agua. Exclusivo para perros. No es apto para consumo humano.",
            img1: "https://d23qt3x1ychzdy.cloudfront.net/dev_images_products/dbf64a31229cc793347ca61c7e53a31b_1708103683.jpg",
            img2: ".jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
            cantidad: 1,
        },
        {
            id: 10,
            title: "Gattino Creamy Poly",
            price: 16.400,
            image: require('../Imagenes/Gattino Creamy Poly.jpeg'),
            category: "snacks",
            mascota: "gato",
            caracteristicas: "Elaborados con real Salmon, Algas Marinas, Agua, extracto de pescado, vitamina E, Espesante. Atún, Aloe Vera, Agua, extracto de pescado, vitamina E, Espesante, colorante.",
            descripcion: "Gattino Creamy es un Snack para tu mascota con ingredientes funcionales que tu gato puede consumir en cualquier momento del día.",
            img1: "https://d23qt3x1ychzdy.cloudfront.net/dev_images_products/68884_Gattino_Creamy_Poly_1626459612_0_500x500.jpeg",
            img2: ".jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
            cantidad: 1,
        },
        {
            id: 11,
            title: "Interpet - Gimnasio Arbol",
            price: 522.500,
            image: require('../Imagenes/Interpet - Gimnasio Arbol.jpg'),
            category: "juguetes",
            mascota: "gato",
            caracteristicas: "Gimnasio fabricado con madera 15mm, tubos resistentes, fique de 6mm, cueva forrada en tapete rascador.",
            descripcion: "Gimnasio con 5 lugares para descansar, cuatro dentro del tronco y uno en la parte superior con vista de 360°. Tamaño de la mascota: Todos los Tamaños. Etapa de la vida: Todas las Edades.",
            img1: "https://d23qt3x1ychzdy.cloudfront.net/dev_images_products/1fc810ebde843f68f7edad9e4c2c6535_1703007304.jpg",
            img2: ".jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
            cantidad: 1,
        },
    ],
};

export default Data;